export const weatherDataFields = [
  { key: "temperature", label: "Temperature" },
  { key: "temperatureApparent", label: "Apparent Temperature" },
  { key: "dewPoint", label: "Dew Point" },
  { key: "humidity", label: "Humidity" },
  { key: "windSpeed", label: "Wind Speed" },
  { key: "windDirection", label: "Wind Direction" },
  { key: "windGust", label: "Wind Gust" },
  { key: "pressureSurfaceLevel", label: "Surface Pressure" },
  { key: "pressureSeaLevel", label: "Sea Level Pressure" },
  { key: "precipitationIntensity", label: "Precipitation Intensity" },
  { key: "rainIntensity", label: "Rain Intensity" },
  { key: "freezingRainIntensity", label: "Freezing Rain Intensity" },
  { key: "snowIntensity", label: "Snow Intensity" },
  { key: "sleetIntensity", label: "Sleet Intensity" },
  { key: "precipitationProbability", label: "Precipitation Probability" },
  { key: "precipitationType", label: "Precipitation Type" },
  { key: "rainAccumulation", label: "Rain Accumulation" },
  { key: "snowAccumulation", label: "Snow Accumulation" },
  { key: "snowAccumulationLwe", label: "Snow Accumulation LWE" },
  { key: "snowDepth", label: "Snow Depth" },
  { key: "sleetAccumulation", label: "Sleet Accumulation" },
  { key: "sleetAccumulationLwe", label: "Sleet Accumulation LWE" },
  { key: "iceAccumulationS", label: "Ice Accumulation" },
  { key: "iceAccumulationLwe", label: "Ice Accumulation LWE" },
  { key: "sunriseTime", label: "Sunrise Time" },
  { key: "sunsetTime", label: "Sunset Time" },
  { key: "visibility", label: "Visibility" },
  { key: "cloudCover", label: "Cloud Cover" },
  { key: "cloudBase", label: "Cloud Base" },
  { key: "cloudCeiling", label: "Cloud Ceiling" },
  { key: "moonPhase", label: "Moon Phase" },
  { key: "uvIndex", label: "UV Index" },
  { key: "uvHealthConcern", label: "UV Health Concern" },
  { key: "gdd10To30", label: "Growing Degree Days 10-30" },
  { key: "gdd10To31", label: "Growing Degree Days 10-31" },
  { key: "gdd08To30", label: "Growing Degree Days 8-30" },
  { key: "gdd03To25", label: "Growing Degree Days 3-25" },
  { key: "weatherCodeFullDay", label: "Full Day Weather Code" },
  { key: "weatherCodeDay", label: "Day Weather Code" },
  { key: "weatherCodeNight", label: "Night Weather Code" },
  { key: "weatherCode", label: "Weather Code" },
  { key: "thunderstormProbability", label: "Thunderstorm Probability" },
  { key: "ezHeatStressIndex", label: "Heat Stress Index" },
];
